# Copyright (c) 2016-2017 Anki, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License in the file LICENSE.txt or at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Autogenerated python message buffer code.
Source: clad/types/behaviorSystem/behaviorObjectives.clad
Full command line: '../tools/message-buffers/emitters/Python_emitter.py' '-C' './src/' '-I' '../robot/clad/src/' '../coretech/vision/clad/src/' '../coretech/common/clad/src/' '../lib/util/source/anki/clad' '-o' '../generated/cladPython//' 'clad/types/behaviorSystem/behaviorObjectives.clad'
"""

from __future__ import absolute_import
from __future__ import print_function

def _modify_path():
  import inspect, os, sys
  search_paths = [
    '../../..',
    '../../../../../tools/message-buffers/support/python',
  ]
  currentpath = os.path.abspath(os.path.dirname(inspect.getfile(inspect.currentframe())))
  for search_path in search_paths:
    search_path = os.path.normpath(os.path.abspath(os.path.realpath(os.path.join(currentpath, search_path))))
    if search_path not in sys.path:
      sys.path.insert(0, search_path)
_modify_path()

import msgbuffers

Anki = msgbuffers.Namespace()
Anki.Cozmo = msgbuffers.Namespace()

class BehaviorObjective(object):
  "Automatically-generated int_32 enumeration."
  Unknown                      = 0
  AnimationPlayed              = 1
  BlockRolled                  = 2
  BuiltPyramid                 = 3
  DroveAsIntended              = 4
  EnrolledFaceWithName         = 5
  FireTruckAlarmPerformed      = 6
  FistBumpComplete             = 7
  FistBumpSuccess              = 8
  FistBumpLeftHanging          = 9
  FoundFace                    = 10
  GatheredCubes                = 11
  InteractedWithFace           = 12
  KnockedOverBlocks            = 13
  LaserPounced                 = 14
  LaserTracked                 = 15
  PeekABooComplete             = 16
  PeekABooSuccess              = 17
  PerformedWorkout             = 18
  PerformedStrongWorkout       = 19
  PickedupBlock                = 20
  PickedUpAndPutDownBlock      = 21
  PoppedWheelie                = 22
  PouncedAndCaught             = 23
  PutDownBlock                 = 24
  ReactedAcknowledgedCubeMoved = 25
  ReactedAcknowledgedFace      = 26
  ReactedAcknowledgedObject    = 27
  ReactedToCliff               = 28
  ReactedToFrustration         = 29
  ReactedToOnCharger           = 30
  ReactedToPickup              = 31
  ReactedToPoke                = 32
  ReactedToRobotOnBack         = 33
  ReactedToRobotOnFace         = 34
  ReactedToRobotOnSide         = 35
  ReactedToRobotShaken         = 36
  ReactedToUnexpectedMovement  = 37
  RequestedGame                = 38
  Singing                      = 39
  StackedBlock                 = 40
  Count                        = 41

Anki.Cozmo.BehaviorObjective = BehaviorObjective
del BehaviorObjective


