# Copyright (c) 2016-2017 Anki, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License in the file LICENSE.txt or at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Autogenerated python message buffer code.
Source: clad/types/liveIdleAnimationParameters.clad
Full command line: '../tools/message-buffers/emitters/Python_emitter.py' '-C' './src/' '-I' '../robot/clad/src/' '../coretech/vision/clad/src/' '../coretech/common/clad/src/' '../lib/util/source/anki/clad' '-o' '../generated/cladPython//' 'clad/types/liveIdleAnimationParameters.clad'
"""

from __future__ import absolute_import
from __future__ import print_function

def _modify_path():
  import inspect, os, sys
  search_paths = [
    '../..',
    '../../../../tools/message-buffers/support/python',
  ]
  currentpath = os.path.abspath(os.path.dirname(inspect.getfile(inspect.currentframe())))
  for search_path in search_paths:
    search_path = os.path.normpath(os.path.abspath(os.path.realpath(os.path.join(currentpath, search_path))))
    if search_path not in sys.path:
      sys.path.insert(0, search_path)
_modify_path()

import msgbuffers

Anki = msgbuffers.Namespace()
Anki.Cozmo = msgbuffers.Namespace()

class LiveIdleAnimationParameter(object):
  "Automatically-generated uint_8 enumeration."
  BlinkSpacingMinTime_ms       = 0
  BlinkSpacingMaxTime_ms       = 1
  TimeBeforeWiggleMotions_ms   = 2
  BodyMovementSpacingMin_ms    = 3
  BodyMovementSpacingMax_ms    = 4
  BodyMovementDurationMin_ms   = 5
  BodyMovementDurationMax_ms   = 6
  BodyMovementSpeedMinMax_mmps = 7
  BodyMovementStraightFraction = 8
  LiftMovementDurationMin_ms   = 9
  LiftMovementDurationMax_ms   = 10
  LiftMovementSpacingMin_ms    = 11
  LiftMovementSpacingMax_ms    = 12
  LiftHeightMean_mm            = 13
  LiftHeightVariability_mm     = 14
  HeadMovementDurationMin_ms   = 15
  HeadMovementDurationMax_ms   = 16
  HeadMovementSpacingMin_ms    = 17
  HeadMovementSpacingMax_ms    = 18
  HeadAngleVariability_deg     = 19
  EyeDartSpacingMinTime_ms     = 20
  EyeDartSpacingMaxTime_ms     = 21
  EyeDartMaxDistance_pix       = 22
  EyeDartMinScale              = 23
  EyeDartMaxScale              = 24
  EyeDartMinDuration_ms        = 25
  EyeDartMaxDuration_ms        = 26
  EyeDartOuterEyeScaleIncrease = 27
  EyeDartUpMaxScale            = 28
  EyeDartDownMinScale          = 29
  NumParameters                = 30

Anki.Cozmo.LiveIdleAnimationParameter = LiveIdleAnimationParameter
del LiveIdleAnimationParameter


